stepperMotorInit();
stepperMotorSetStep( unsigned int stepValue);
stepperMotorGetStep( );
stepperMotorSetSpeed(unsigned int speedValue);
stepperMotorGetSpeed( );
stepperMotorStart();
stepperMotorStop();
stepperMotorReset();
stepperMotorGetTorque();
stepperMotorSetTorque();
stepperMotorGetCurrentConsumption();
stepperMotorGetCurrentVoltage();