int stepperMotorInit();
int stepperMotorSetStep( unsigned int stepValue);
unsigned int stepperMotorGetStep( );
int stepperMotorSetSpeed(unsigned int speedValue);
unsigned int stepperMotorGetSpeed( );
void stepperMotorStart();
void stepperMotorStop();
int stepperMotorReset();
int stepperMotorGetTorque();
int stepperMotorSetTorque();
int stepperMotorGetCurrentConsumption();
int stepperMotorGetCurrentVoltage();
